#pragma once

#include <ringos/types.h>

#ifdef __cplusplus
extern "C" {
#endif

enum ringos_status
{
  RINGOS_STATUS_OK = 0,
  RINGOS_STATUS_INVALID_ARGUMENT = -1,
  RINGOS_STATUS_BAD_HANDLE = -2,
  RINGOS_STATUS_WRONG_TYPE = -3,
  RINGOS_STATUS_BUFFER_TOO_SMALL = -4,
  RINGOS_STATUS_PEER_CLOSED = -5,
  RINGOS_STATUS_WOULD_BLOCK = -6,
  RINGOS_STATUS_TIMED_OUT = -7,
  RINGOS_STATUS_NO_MEMORY = -8,
  RINGOS_STATUS_FAULT = -9,
  RINGOS_STATUS_NOT_SUPPORTED = -10,
  RINGOS_STATUS_BAD_STATE = -11,
  RINGOS_STATUS_NOT_FOUND = -12,
};

#ifdef __cplusplus
}
#endif
