function(ringos_get_default_compiler_root out_compiler_root)
  if(WIN32 AND DEFINED ENV{LOCALAPPDATA})
    file(TO_CMAKE_PATH "$ENV{LOCALAPPDATA}/ringos/toolchain" compiler_root)
  elseif(DEFINED ENV{HOME})
    file(TO_CMAKE_PATH "$ENV{HOME}/.cache/ringos/toolchain" compiler_root)
  else()
    get_filename_component(repo_root ${CMAKE_CURRENT_LIST_DIR}/../.. ABSOLUTE)
    set(compiler_root ${repo_root}/build/installed-toolchain)
  endif()

  set(${out_compiler_root} ${compiler_root} PARENT_SCOPE)
endfunction()

function(ringos_resolve_llvm_root out_compiler_root)
  if(DEFINED RINGOS_PREVIOUS_STAGE_TOOLCHAIN_ROOT AND NOT RINGOS_PREVIOUS_STAGE_TOOLCHAIN_ROOT STREQUAL "")
    set(compiler_root ${RINGOS_PREVIOUS_STAGE_TOOLCHAIN_ROOT})
  elseif(DEFINED RINGOS_LLVM_TOOLCHAIN_ROOT AND NOT RINGOS_LLVM_TOOLCHAIN_ROOT STREQUAL "")
    set(compiler_root ${RINGOS_LLVM_TOOLCHAIN_ROOT})
  elseif(DEFINED ENV{RINGOS_PREVIOUS_STAGE_TOOLCHAIN_ROOT} AND NOT "$ENV{RINGOS_PREVIOUS_STAGE_TOOLCHAIN_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{RINGOS_PREVIOUS_STAGE_TOOLCHAIN_ROOT}" compiler_root)
  elseif(DEFINED ENV{RINGOS_LLVM_TOOLCHAIN_ROOT} AND NOT "$ENV{RINGOS_LLVM_TOOLCHAIN_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{RINGOS_LLVM_TOOLCHAIN_ROOT}" compiler_root)
  else()
    ringos_get_default_compiler_root(compiler_root)
  endif()

  set(${out_compiler_root} ${compiler_root} PARENT_SCOPE)
endfunction()

function(ringos_find_llvm_tool tool_name out_tool_path)
  ringos_resolve_llvm_root(compiler_root)
  find_program(tool_path NAMES ${ARGN} HINTS ${compiler_root}/bin NO_DEFAULT_PATH REQUIRED)
  set(${out_tool_path} ${tool_path} PARENT_SCOPE)
endfunction()
