include_guard(GLOBAL)

get_filename_component(RINGOS_LLVM_ROOT_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

function(ringos_get_default_llvm_source_dir_name out_source_dir_name)
  if(DEFINED RINGOS_LLVM_SOURCE_ARCHIVE AND NOT RINGOS_LLVM_SOURCE_ARCHIVE STREQUAL "")
    get_filename_component(source_archive_name ${RINGOS_LLVM_SOURCE_ARCHIVE} NAME)
  elseif(DEFINED ENV{RINGOS_LLVM_SOURCE_ARCHIVE} AND NOT "$ENV{RINGOS_LLVM_SOURCE_ARCHIVE}" STREQUAL "")
    get_filename_component(source_archive_name "$ENV{RINGOS_LLVM_SOURCE_ARCHIVE}" NAME)
  elseif(DEFINED RINGOS_LLVM_REF AND NOT RINGOS_LLVM_REF STREQUAL "")
    set(source_archive_name llvm-project-${RINGOS_LLVM_REF}.tar.gz)
  elseif(DEFINED ENV{RINGOS_LLVM_REF} AND NOT "$ENV{RINGOS_LLVM_REF}" STREQUAL "")
    set(source_archive_name llvm-project-$ENV{RINGOS_LLVM_REF}.tar.gz)
  else()
    set(source_archive_name llvm-project-3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff.tar.gz)
  endif()

  if(source_archive_name MATCHES "\\.tar\\.gz$")
    string(REGEX REPLACE "\\.tar\\.gz$" "" source_dir_name ${source_archive_name})
  elseif(source_archive_name MATCHES "\\.tar\\.xz$")
    string(REGEX REPLACE "\\.tar\\.xz$" "" source_dir_name ${source_archive_name})
  elseif(source_archive_name MATCHES "\\.tgz$")
    string(REGEX REPLACE "\\.tgz$" "" source_dir_name ${source_archive_name})
  elseif(source_archive_name MATCHES "\\.zip$")
    string(REGEX REPLACE "\\.zip$" "" source_dir_name ${source_archive_name})
  else()
    get_filename_component(source_dir_name ${source_archive_name} NAME_WE)
  endif()

  set(${out_source_dir_name} ${source_dir_name} PARENT_SCOPE)
endfunction()

function(ringos_get_default_compiler_root out_compiler_root)
  if(DEFINED ENV{RINGOS_TOOLCHAIN_ROOT} AND NOT "$ENV{RINGOS_TOOLCHAIN_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{RINGOS_TOOLCHAIN_ROOT}" compiler_root)
  else()
    set(compiler_root ${RINGOS_LLVM_ROOT_REPO_ROOT}/build/toolchain)
  endif()

  set(${out_compiler_root} ${compiler_root} PARENT_SCOPE)
endfunction()

function(ringos_resolve_llvm_root out_compiler_root)
  if(DEFINED RINGOS_ACTIVE_LLVM_ROOT AND NOT RINGOS_ACTIVE_LLVM_ROOT STREQUAL "" AND EXISTS ${RINGOS_ACTIVE_LLVM_ROOT}/bin/clang)
    set(compiler_root ${RINGOS_ACTIVE_LLVM_ROOT})
  elseif(DEFINED ENV{RINGOS_ACTIVE_LLVM_ROOT} AND NOT "$ENV{RINGOS_ACTIVE_LLVM_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{RINGOS_ACTIVE_LLVM_ROOT}" env_active_llvm_root)

    if(EXISTS ${env_active_llvm_root}/bin/clang)
      set(compiler_root ${env_active_llvm_root})
    endif()
  elseif(DEFINED RINGOS_TOOLCHAIN_ROOT AND NOT RINGOS_TOOLCHAIN_ROOT STREQUAL "" AND EXISTS ${RINGOS_TOOLCHAIN_ROOT}/bin/clang)
    set(compiler_root ${RINGOS_TOOLCHAIN_ROOT})
  elseif(DEFINED ENV{RINGOS_TOOLCHAIN_ROOT} AND NOT "$ENV{RINGOS_TOOLCHAIN_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{RINGOS_TOOLCHAIN_ROOT}" env_toolchain_root)

    if(EXISTS ${env_toolchain_root}/bin/clang)
      set(compiler_root ${env_toolchain_root})
    endif()
  endif()

  if(NOT DEFINED compiler_root OR NOT EXISTS ${compiler_root}/bin/clang)
    set(compiler_root ${RINGOS_LLVM_ROOT_REPO_ROOT}/build/toolchain-build/bootstrap-llvm/install)
  endif()

  set(${out_compiler_root} ${compiler_root} PARENT_SCOPE)
endfunction()

function(ringos_get_active_llvm_root out_llvm_root)
  ringos_resolve_llvm_root(llvm_root)
  set(${out_llvm_root} ${llvm_root} PARENT_SCOPE)
endfunction()

function(ringos_resolve_llvm_source_root out_source_root)
  if(DEFINED RINGOS_LLVM_SOURCE_DIR AND NOT RINGOS_LLVM_SOURCE_DIR STREQUAL "" AND EXISTS ${RINGOS_LLVM_SOURCE_DIR})
    set(source_root ${RINGOS_LLVM_SOURCE_DIR})
  elseif(DEFINED ENV{RINGOS_LLVM_SOURCE_DIR} AND NOT "$ENV{RINGOS_LLVM_SOURCE_DIR}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{RINGOS_LLVM_SOURCE_DIR}" env_source_root)

    if(EXISTS ${env_source_root})
      set(source_root ${env_source_root})
    endif()
  endif()

  if(NOT DEFINED source_root)
    ringos_get_default_llvm_source_dir_name(source_dir_name)
    set(versioned_source_root ${RINGOS_LLVM_ROOT_REPO_ROOT}/build/toolchain-build/bootstrap-llvm/src/${source_dir_name})

    if(EXISTS ${versioned_source_root})
      set(source_root ${versioned_source_root})
    endif()
  endif()

  if(DEFINED source_root)
    set(${out_source_root} ${source_root} PARENT_SCOPE)
  else()
    set(${out_source_root} "" PARENT_SCOPE)
  endif()
endfunction()

function(ringos_find_llvm_tool tool_name out_tool_path)
  ringos_resolve_llvm_root(compiler_root)
  string(MAKE_C_IDENTIFIER "${tool_name}" tool_path_suffix)
  set(tool_path_var "ringos_found_llvm_tool_${tool_path_suffix}")
  unset(${tool_path_var})
  unset(${tool_path_var} CACHE)

  find_program(${tool_path_var} NAMES ${ARGN} HINTS ${compiler_root}/bin NO_DEFAULT_PATH REQUIRED)
  set(tool_path ${${tool_path_var}})
  set(${out_tool_path} ${tool_path} PARENT_SCOPE)
endfunction()
