from __future__ import annotations

import pathlib


def parse_scalar(raw_value: str) -> str:
    value = raw_value.strip()

    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]

    return value


def parse_key_value(text: str) -> tuple[str, str]:
    key, separator, value = text.partition(":")

    if separator != ":":
        raise ValueError(f"expected key/value pair, got: {text}")

    return key.strip(), parse_scalar(value)


def parse_definition(path: pathlib.Path) -> dict[str, object]:
    module_name: str | None = None
    exports: list[dict[str, str]] = []
    current_export: dict[str, str] | None = None
    in_exports = False

    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.split("#", 1)[0].rstrip()

        if not line.strip():
            continue

        indent = len(line) - len(line.lstrip(" "))
        content = line.strip()

        if indent == 0:
            current_export = None

            if content == "exports:":
                in_exports = True
                continue

            key, value = parse_key_value(content)

            if key != "dll":
                raise ValueError(f"{path}:{line_number}: unsupported top-level key '{key}'")

            module_name = value
            continue

        if not in_exports:
            raise ValueError(f"{path}:{line_number}: unexpected indentation before exports block")

        if indent == 2 and content.startswith("- "):
            current_export = {}
            exports.append(current_export)
            key, value = parse_key_value(content[2:])
            current_export[key] = value
            continue

        if indent == 4 and current_export is not None:
            key, value = parse_key_value(content)
            current_export[key] = value
            continue

        raise ValueError(f"{path}:{line_number}: unsupported line '{raw_line}'")

    if not module_name:
        raise ValueError(f"{path}: missing dll name")

    for export in exports:
        if "name" not in export or "syscall" not in export:
            raise ValueError(f"{path}: every export needs both name and syscall")

    return {
        "dll": module_name,
        "exports": exports,
    }


def generate(definitions_dir: pathlib.Path, output_dir: pathlib.Path) -> None:
    definitions = [parse_definition(path) for path in sorted(definitions_dir.glob("*.yaml"))]
    header_path = output_dir / "x64_win32_dll_exports.h"
    source_path = output_dir / "x64_win32_dll_exports.cpp"

    header_path.write_text(
        "// Generated by generate_win32_emulation.py. Do not edit by hand.\n"
        "#pragma once\n\n"
        "#if defined(__STDC_HOSTED__) && __STDC_HOSTED__\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "#else\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n"
        "#endif\n\n"
        "struct x64_win32_dll_export\n"
        "{\n"
        "  const char* dll_name;\n"
        "  const char* symbol_name;\n"
        "  uint64_t syscall_number;\n"
        "};\n\n"
        "const x64_win32_dll_export* get_x64_win32_dll_exports(size_t* out_count);\n\n",
        encoding="utf-8",
    )

    lines = [
        "// Generated by generate_win32_emulation.py. Do not edit by hand.",
        '#include "x64_win32_dll_exports.h"',
        "",
        '#include "user_space.h"',
        "",
        "namespace",
        "{",
        "  constexpr x64_win32_dll_export X64_WIN32_DLL_EXPORTS[] {",
    ]

    for definition in definitions:
        for export in definition["exports"]:
            lines.append(
                f'    {{"{definition["dll"]}", "{export["name"]}", {export["syscall"]}}},')

    lines.extend(
        [
            "  };",
            "}",
            "",
            "const x64_win32_dll_export* get_x64_win32_dll_exports(size_t* out_count)",
            "{",
            "  if (out_count != nullptr)",
            "  {",
            "    *out_count = sizeof(X64_WIN32_DLL_EXPORTS) / sizeof(X64_WIN32_DLL_EXPORTS[0]);",
            "  }",
            "",
            "  return X64_WIN32_DLL_EXPORTS;",
            "}",
            "",
        ]
    )

    source_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    base_dir = pathlib.Path(__file__).resolve().parent
    generate(base_dir / "definitions", base_dir / "generated")