get_filename_component(RINGOS_KERNEL_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

if(NOT DEFINED RINGOS_KERNEL_TOOLCHAIN_ROOT)
  if(DEFINED RINGOS_TOOLCHAIN_ROOT AND NOT RINGOS_TOOLCHAIN_ROOT STREQUAL "")
    set(RINGOS_KERNEL_TOOLCHAIN_ROOT "${RINGOS_TOOLCHAIN_ROOT}")
  elseif(DEFINED ENV{RINGOS_TOOLCHAIN_ROOT} AND NOT "$ENV{RINGOS_TOOLCHAIN_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{RINGOS_TOOLCHAIN_ROOT}" RINGOS_KERNEL_TOOLCHAIN_ROOT)
  else()
    set(RINGOS_KERNEL_TOOLCHAIN_ROOT "${RINGOS_KERNEL_SOURCE_ROOT}/build/toolchain")
  endif()
endif()

if(NOT EXISTS "${RINGOS_KERNEL_TOOLCHAIN_ROOT}/bin/clang")
  message(FATAL_ERROR
    "Kernel builds require an extracted toolchain bundle under ${RINGOS_KERNEL_TOOLCHAIN_ROOT}. "
    "Run tests/download-latest-toolchain.sh first.")
endif()

find_program(RINGOS_KERNEL_CLANG
  NAMES clang clang-18 clang-17
  HINTS "${RINGOS_KERNEL_TOOLCHAIN_ROOT}/bin"
  NO_DEFAULT_PATH
  REQUIRED)
find_program(RINGOS_KERNEL_CLANGXX
  NAMES clang++ clang++-18 clang++-17
  HINTS "${RINGOS_KERNEL_TOOLCHAIN_ROOT}/bin"
  NO_DEFAULT_PATH
  REQUIRED)
find_program(RINGOS_KERNEL_LD_LLD
  NAMES ld.lld ld.lld-18 ld.lld-17
  HINTS "${RINGOS_KERNEL_TOOLCHAIN_ROOT}/bin"
  NO_DEFAULT_PATH
  REQUIRED)
find_program(CMAKE_OBJCOPY
  NAMES llvm-objcopy llvm-objcopy-18 llvm-objcopy-17
  HINTS "${RINGOS_KERNEL_TOOLCHAIN_ROOT}/bin"
  NO_DEFAULT_PATH
  REQUIRED)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ${RINGOS_KERNEL_SYSTEM_PROCESSOR})

set(CMAKE_C_COMPILER ${RINGOS_KERNEL_CLANG})
set(CMAKE_CXX_COMPILER ${RINGOS_KERNEL_CLANGXX})
set(CMAKE_ASM_COMPILER ${RINGOS_KERNEL_CLANG})

set(CMAKE_C_COMPILER_TARGET ${RINGOS_KERNEL_TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET ${RINGOS_KERNEL_TARGET_TRIPLE})
set(CMAKE_ASM_COMPILER_TARGET ${RINGOS_KERNEL_TARGET_TRIPLE})

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES RINGOS_TOOLCHAIN_ROOT RINGOS_KERNEL_TOOLCHAIN_ROOT)

set(CMAKE_C_LINK_EXECUTABLE "\"${RINGOS_KERNEL_LD_LLD}\" <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "\"${RINGOS_KERNEL_LD_LLD}\" <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_ASM_LINK_EXECUTABLE "\"${RINGOS_KERNEL_LD_LLD}\" <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

add_compile_options(-ffreestanding -fno-exceptions -fno-rtti -Wall -Wextra -Wpedantic)
